// src/app/models/booking.model.ts
export interface Booking {
  _id?: string; // _id is optional since it will be generated by MongoDB
  fullName: string;
  age: number | null; // Allow age to be number or null
  phoneNumber: string;
  bookingNumber?: string; // This might be generated by the server, so it's optional
  visit: {
    _id: string;
    doctorName: string;
    specialty: string;
    visitDate: Date;
  };
}
